# Generated by Django 6.0 on 2025-12-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Page Category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Page Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publish',
            field=models.DateField(verbose_name='Page Published Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(verbose_name='Post Published Date'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(verbose_name='Song Duration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Song Title'),
        ),
    ]
