# Generated by Django 5.2.8 on 2025-11-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
