# Generated by Django 5.2.7 on 2025-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default='meals/images/default.png', upload_to='meals/images'),
        ),
    ]
